service_error:
  10001: 用户名不能为空
  10002: ERR_USER_NAME_THE_MAXIMUM_LENGTH_OF_32
  10003: 密码不能为空
  10004: ERR_USER_PASSWORD_THE_MAXIMUM_LENGTH_OF_64
  10005: ERR_USER_NICKNAME_CANNOT_BE_BLANK
  10006: ERR_USER_NICKNAME_THE_MAXIMUM_LENGTH_OF_32
  10007: ERR_USER_NAME_NOT_UNIQUE
  10008: ERR_USER_NICKNAME_NOT_UNIQUE
  10009: 账号或密码错误


  11001: 类别名称不能为空
  11002: ERR_CATEGORY_SEQ_CANNOT_BE_BLANK
  11003: 类别名称长度超过限制
  11004: 类别名称已存在


  12001: 标签名称不能为空
  12002: 标签名称长度超过限制
  12003: 标签名称已存在


  13001: 文章标题不能为空
  13002: 文章类型不能为空
  13003: 文章类别不能为空
  13004: 文章标签不能为空
  13005: 文章标题长度不能超过64
  13006: 文章来源长度不能超过64
  13007: 文章来源路径不能超过128
  13008: 文章标签长度不能超过64
  13009: 文章摘要长度不能超过255
  13010: 文章附件路径长度不能超过128
  13011: 文章类型值不合法
  13012: 文章状态值不合法