service_error:
    10001: ERR_USER_NAME_CANNOT_BE_BLANK
    10002: ERR_USER_NAME_THE_MAXIMUM_LENGTH_OF_32
    10003: ERR_USER_PASSWORD_CANNOT_BE_BLANK
    10004: ERR_USER_PASSWORD_THE_MAXIMUM_LENGTH_OF_64
    10005: ERR_USER_NICKNAME_CANNOT_BE_BLANK
    10006: ERR_USER_NICKNAME_THE_MAXIMUM_LENGTH_OF_32

    11001: ERR_CATEGORY_NAME_CANNOT_BE_BLANK
    11002: ERR_CATEGORY_SEQUENCE_CANNOT_BE_BLANK
    11003: ERR_CATEGORY_NAME_THE_MAXIMUM_LENGTH_OF_32