service_error:
  10001: 用户名不能为空
  10002: ERR_USER_NAME_THE_MAXIMUM_LENGTH_OF_32
  10003: 密码不能为空
  10004: ERR_USER_PASSWORD_THE_MAXIMUM_LENGTH_OF_64
  10005: ERR_USER_NICKNAME_CANNOT_BE_BLANK
  10006: ERR_USER_NICKNAME_THE_MAXIMUM_LENGTH_OF_32
  10007: ERR_USER_NAME_NOT_UNIQUE
  10008: ERR_USER_NICKNAME_NOT_UNIQUE
  10009: 账号或密码错误


  11001: 类别名称不能为空
  11002: ERR_CATEGORY_SEQ_CANNOT_BE_BLANK
  11003: 类别名称长度超过限制
  11004: 类别名称已存在

  12001: 标签名称不能为空
  12002: 标签名称长度超过限制
  12003: 标签名称已存在

  

