default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: myblog_production