update_common_tags_cache_job:
  cron: "* 1 * * *" # 每天凌晨一点更新一次常用标签缓存
  class: "UpdateCommonTagsCacheJob"
  queue: low

sync_article_pv_job:
  cron: "* 1 * * *" # 每天凌晨一点同步一次文章访问量
  class: "SyncArticlePvJob"
  queue: default

# 第一列 分钟： 1——59
# 第二列 小时： 1——23(0表示子夜)
# 第三列 日 ： 1——31
# 第四列 月 ： 1——12
# 第五列 星期： 星期0——6(0表示星期天，1表示星期一、以此类推)